version: "3.7"

services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - skynet
  exercicio:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - rabbit
    networks:
      - skynet
networks:
  skynet: