
package br.ufpe.cin;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FIPEServer", targetNamespace = "http://cin.ufpe.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FIPEServer {


    /**
     * 
     * @return
     *     returns java.util.List<br.ufpe.cin.Brand>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "brands", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.Brands")
    @ResponseWrapper(localName = "brandsResponse", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.BrandsResponse")
    @Action(input = "http://cin.ufpe.br/FIPEServer/brandsRequest", output = "http://cin.ufpe.br/FIPEServer/brandsResponse")
    public List<Brand> brands();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.ufpe.cin.Car>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "carsByBrand", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.CarsByBrand")
    @ResponseWrapper(localName = "carsByBrandResponse", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.CarsByBrandResponse")
    @Action(input = "http://cin.ufpe.br/FIPEServer/carsByBrandRequest", output = "http://cin.ufpe.br/FIPEServer/carsByBrandResponse")
    public List<Car> carsByBrand(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "carPrices", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.CarPrices")
    @ResponseWrapper(localName = "carPricesResponse", targetNamespace = "http://cin.ufpe.br/", className = "br.ufpe.cin.CarPricesResponse")
    @Action(input = "http://cin.ufpe.br/FIPEServer/carPricesRequest", output = "http://cin.ufpe.br/FIPEServer/carPricesResponse")
    public List<String> carPrices(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
